spring:
  redis:
    host: localhost
    port: 6379
    password: ''
  session:
    store-type: redis
    redis:
      flush-mode: on_save

server:
  port: 8080

logging:
  level:
    edu.pasudo123.study.sessionconfig: INFO
