
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pets;

CREATE TABLE users (
    id BIGINT IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    age SMALLINT NOT NULL,
    gender ENUM('MAN', 'WOMAN') NOT NULL
);


CREATE TABLE pets (
    id BIGINT NOT NULL IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    users_id BIGINT NOT NULL
);

ALTER TABLE PETS ADD CONSTRAINT fk_pets_users_idx FOREIGN KEY (users_id) REFERENCES users(id);
